---
platform: linux

image: docker:///cloudfoundry/diego-pipeline

inputs:
  - name: deployments-diego
  - name: cephfs-bosh-release-tarball
  - name: efs-volume-release-tarball
  - name: local-volume-release-tarball

outputs: []

params: []

run:
  path: cephfs-bosh-release/scripts/ci/update_runtime_config.sh
