name:
director_uuid:

releases:
  - name: 
    version: latest

jobs:
  - name:
    instances: 1
    resource_pool: ceph-resourcepool
    networks:
      - name: ceph-net
        static_ips:
    persistent_disk: 25000 # for consul
    templates:
      - {release: , name: }
    properties:
      cephdriver:
        drivers_path:
        cephfs_ip:
        cephfs_keyring:

networks:
  - name: ceph-net
    type: manual
    subnets:
      - range: 10.244.8.0/24
        gateway: 10.244.8.1
        static:
        - 10.244.8.2
        - 10.244.8.3
        cloud_properties: {}

resource_pools:
  - name: ceph-resourcepool
    network: ceph-net
    cloud_properties: {}
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest

compilation:
  workers: 1
  network: ceph-net
  cloud_properties: {}

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
