name: 
director_uuid: 

releases:
  - name: cephfs-bosh-release
    version: latest

jobs:
  - name: cephfs
    instances: 1
    resource_pool: ceph-resourcepool
    networks:
      - name: ceph-subnet
        default: [dns, gateway]

    persistent_disk: 25000 # for consul
    templates:
      - {release: cephfs-bosh-release, name: cephfs}
    properties:
      ceph:
        key: value

networks:
  - name: ceph-subnet
    type: manual
    subnets:
      - range: 10.0.0.0/24
        gateway: 10.0.0.1
        dns: [10.0.0.2]
        reserved:
        - 10.0.0.2 - 10.0.0.9
        static:
        - 10.0.0.10 - 10.0.0.100
        cloud_properties:
          subnet: subnet-98b118ee

resource_pools:
  - name: ceph-resourcepool
    network: ceph-subnet
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m3.medium

compilation:
  workers: 1
  network: ceph-subnet
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m3.large
    ephemeral_disk:
      size: 10000 # in MB
      type: gp2

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
